name: Build apk for avni client
on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  generate-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Install Watchman
        run: |
          sudo apt-get update
          sudo apt-get install -y watchman

      - name: Generate keystore
        run: |
          cd packages/openchs-android/android/app
          keytool -genkeypair -storepass password -storetype PKCS12 -keyalg RSA -keysize 2048 -dname "CN=server" -alias bahmni -ext "SAN:c=DNS:localhost,IP:127.0.0.1" -keystore bahmni-release-key.keystore

      - name: Run make release_urlconfig_universal
        run: |
          export BAHMNI_KEYSTORE_PASSWORD=password
          export BAHMNI_KEY_PASSWORD=password
          make release_no_env_universal flavor='bahmni'

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v2
        with:
          name: bahmni-release
          path: packages/openchs-android/android/app/build/outputs/apk/bahmni/release

